# Generated by Django 5.1.2 on 2024-10-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(blank=True, choices=[('recruiter', 'Recruiter'), ('volunteer', 'Volunteer')], max_length=20),
        ),
    ]
